theme: jekyll-theme-minimal
title: Sandeep Mewara
logo: /assets/img/sandeep-mewara.png
google_analytics:
description: Here I am
linkedin: sandeepmewara
twitter_username: _smewara
github_username:  sandeep-mewara
